version: "3.9"

services:
  db:
    image: mysqlcompose
    restart: always
    env_file:
      - ./config/db.env 
    ports:
      - "3307:3306"
    networks:
      - dockercompose

  backend:
    image: flaskcompose
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - dockercompose

networks:
  dockercompose:
    driver: bridge
