services:                 # Define os serviços que compõem a aplicação (containers a serem criados)

  db:                     # Serviço de banco de dados (MySQL)
    image: mysql:8.0       # Usa a imagem oficial do MySQL na versão 8.0
    container_name: mysql_db   # Define um nome fixo para o container (facilita nos comandos e logs)
    restart: always        # Garante que o container reinicie automaticamente em caso de falha
    environment:           # Variáveis de ambiente passadas para o container MySQL
      MYSQL_ROOT_PASSWORD: docker  # Define a senha do usuário root do MySQL
      MYSQL_DATABASE: wordpress    # Cria automaticamente o banco de dados chamado "wordpress"
      MYSQL_USER: docker           # Cria um usuário adicional chamado "docker"
      MYSQL_PASSWORD: docker       # Senha do usuário "docker"
    volumes:              # Monta volumes para persistência de dados do banco
      - db_data:/var/lib/mysql   # Associa o volume "db_data" ao diretório de dados do MySQL dentro do container

  wordpress:              # Serviço da aplicação WordPress
    image: wordpress:latest   # Usa a imagem oficial do WordPress na versão mais recente
    container_name: wordpress_app   # Nome fixo para o container do WordPress
    restart: always        # Reinicia automaticamente em caso de falha
    ports:                 # Mapeamento de portas (host:container)
      - "8080:80"          # Expõe a porta 80 do container (Apache do WP) na porta 8080 do host
    environment:           # Variáveis de ambiente necessárias para o WordPress conectar ao MySQL
      WORDPRESS_DB_HOST: db:3306     # Indica o host e porta do banco (nome do serviço "db" + porta 3306)
      WORDPRESS_DB_USER: docker      # Usuário que o WordPress usará para acessar o banco
      WORDPRESS_DB_PASSWORD: docker  # Senha do usuário do banco
      WORDPRESS_DB_NAME: wordpress   # Nome do banco de dados que o WordPress usará
    depends_on:            # Define dependências entre serviços
      - db                 # Faz o WordPress esperar o container do MySQL iniciar primeiro

volumes:                   # Define volumes persistentes usados pelos serviços
  db_data:                 # Volume nomeado "db_data", armazenará os dados do MySQL
